### ISSUE TITLE
error on training my own data set

### ISSUE THREAD

**Issue by KarLea** [junyanz/iGAN#19]
I am trying to train my own data set. For starting I prepared 1000 pictures and made an hdf5 file based on 64*64. After that I ran the **train_dcgan.py**  file I had an error and I had to modify the n_vis parameter manually to 10 in train_dcgan.py to get it work. But after that I had a new error which I have paste it here:

> 
> Traceback (most recent call last):
>   File "train_dcgan.py", line 71, in <module>
>     grid_real = utils.grid_vis((vaX_vis*255.0).astype(np.uint8), n_grid, n_grid)
>   File "../lib/utils.py", line 138, in grid_vis
>     img[j * h:j * h + h, i * w:i * w + w, :] = x
> ValueError: could not broadcast input array from shape (64,64,3) into shape (0,64,3)

I would be very appreciated if you have any suggestions.

**Comment by junyanz** [comment]
Could you set n_vis as 9 or 16?
