### ISSUE TITLE
qdarkstyle issue (No module named qdarkstyle)

### ISSUE THREAD

**Issue by prmex900** [junyanz/iGAN#26]
hi, i'm running this command after I have installed everything

`iGAN2noui A$ THEANO_FLAGS='device=gpu0, floatX=float32, nvcc.fastmath=True' python iGAN_main.py --model_name outdoor_64`

and get this error. everything is installed as you described. i tried it on macos and ubuntu. same error.

```
Traceback (most recent call last):
  File "iGAN_main.py", line 4, in <module>
    import qdarkstyle
ImportError: No module named qdarkstyle
```

**Comment by junyanz** [comment]
You need to install it via `sudo pip install qdarkstyle`.

**Comment by prmex900** [comment]
> You need to install it via sudo pip install qdarkstyle.

this is exactly what i did. but still nothing

**Comment by junyanz** [comment]
Very interesting. Are you using conda? For conda users, you can try [this](https://anaconda.org/auto/qdarkstyle).

**Comment by prmex900** [comment]
i managed to make it with trying multiple times `sudo pip install qdarkstyle` 

then i got problem with pyqt4 
> no module named pyqt4

solved with `conda install pyqt=4` (only this one worked for me. macos)

then was 
> ModuleNotFoundError: No module named 'dominate'

solved with `pip install dominate`

then there is some other issues I will get back with later
still couldn't run it

**Comment by junyanz** [comment]
Please see the [requirements](https://github.com/junyanz/iGAN#requirements)

**Comment by prmex900** [comment]
yes I knew you will say that. It was installed right before I started. 
I followed every step from requirements. that is why it is all so confusing

after i run `THEANO_FLAGS='device=gpu0, floatX=float32, nvcc.fastmath=True' python iGAN_main.py --model_name outdoor_64`

i get multiple lines like this 

> objc[2430]: Class QCocoaColorPanelDelegate is implemented in both /Users/USERNAME/miniconda2/lib/libQtGui.4.8.7.dylib (0x1027cfde0) and /Users/USERNAME/miniconda2/lib/python2.7/site-packages/cv2/.dylibs/QtGui (0x10a1f6d60). One of the two will be used. Which one is undefined.

and at the end 

> File "iGAN_main.py", line 9, in <module>
    import constrained_opt
  File "/Users/USERNAME/iGAN/constrained_opt.py", line 3, in <module>
    from lib.rng import np_rng
  File "/Users/USERNAME/iGAN/lib/rng.py", line 2, in <module>
    from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
ImportError: No module named theano.sandbox.rng_mrg

**Comment by Praddmobile** [comment]
updated

**Comment by junyanz** [comment]
It seems to be related to Theano. Could you run other Theano [example](https://github.com/Newmu/Theano-Tutorials)/test code? You may want to install this Theano [version](https://github.com/Newmu/dcgan_code/issues/5).  The code was developed around 2016, and the Theano was gone now (not longer supported). Therefore, it is quite hard to compile the code. We are working on a PyTorch version, but it might take some time.

**Comment by prmex900** [comment]
not really, theano gives me struggle=)

**Comment by flutterq** [comment]
[[Solved] No module named ‘qdarkstyle.colorsystem’ in anaconda
](https://exerror.com/no-module-named-qdarkstyle-colorsystem-in-anaconda/)

**Comment by marvelous-dog** [comment]
pip install pyqtdarktheme
